FROM alpine@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c8f30f7e2ccffb48c1e8af
LABEL org.opencontainers.image.source="https://github.com/Makepad-fr/buildgraph"
WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN addgroup -S app && adduser -S app -G app
USER app
HEALTHCHECK --interval=30s --timeout=3s CMD ["true"]
CMD ["./buildgraph"]
